wip(zsh): decouple prompt from omz

diff --git a/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl b/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
--- a/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
+++ b/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
@@ -14,14 +14,17 @@ search-aliases() {
 
 strict_mode(){
   if [[ "$1" != "off" ]]; then
-    set -T # inherit DEBUG and RETURN trap for functions
-    set -C # prevent file overwrite by > &> <>
-    set -E # inherit -e
-    set -e # exit immediately on errors
-    set -u # exit on not assigned variables
-    set -o pipefail # exit on pipe failure
+    ## set -T # inherit DEBUG and RETURN trap for functions
+    ## set -C # prevent file overwrite by > &> <>
+    ## set -E # inherit -e
+    ## set -e # exit immediately on errors
+    ## set -u # exit on not assigned variables
+    ## set -o pipefail # exit on pipe failure
+    set +Ceuo pipefail
+    _debug 'Strict mode enabled'
   else
-    set +TCEeuo pipefail
+    set +Ceuo pipefail
+    _debug 'Strict mode disabled'
   fi
 }
 
