chore(zsh): conditionally display dco ps output and define shell strict mode

diff --git a/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl b/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
--- a/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
+++ b/home/dot_config/zsh/plugins/core/core.plugin.zsh.tmpl
@@ -12,6 +12,18 @@ search-aliases() {
   alias | grep "$1" --color
 }
 
+strict_mode(){
+  if [[ "$1" != "off" ]]; then
+    set -T # inherit DEBUG and RETURN trap for functions
+    set -C # prevent file overwrite by > &> <>
+    set -E # inherit -e
+    set -e # exit immediately on errors
+    set -u # exit on not assigned variables
+    set -o pipefail # exit on pipe failure
+  else
+    set +TCEeuo pipefail
+  fi
+}
 
 # Creates a temp file name and leverages it to swap to files "in place"
 swap() {
